### ISSUE TITLE
How is this used?

### ISSUE THREAD

**Issue by boomcreeper11** [cathaypacific8747/geofs-gpws#1]
How do I use this?

**Comment by cathaypacific8747** [comment]
Currently finished the altitude callouts, currently working on the 'Bank
Angle', 'Caution Terrain', 'Whoop Whoop Pull Up', 'Too Low, flaps', 'Too
low, gear' etc.
ETA would be ~3-5 days, I'll upload the tampermonkey script as soon as I've
finished it.
Thanks!

**Comment by boomcreeper11** [comment]
thx
  
  
   On 19 April 2020 at 16:48 cathaypacific8747 <notifications@github.com> wrote: 
   
   
   Currently finished the altitude callouts, currently working on the 'Bank 
   Angle', 'Caution Terrain', 'Whoop Whoop Pull Up', 'Too Low, flaps', 'Too 
   low, gear' etc. 
   ETA would be ~3-5 days, I'll upload the tampermonkey script as soon as I've 
   finished it. 
   Thanks!
